export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Looking for a roommate',
        content: 'Student is looking for someone to split costs of rent. Flat near university.',
        date: '10.10.2010',
        updateDate: '11.10.2010',
        mail: 'johndoe@example.com',
        phone: 123456789,
        status: 'published',
        image: 'https://images.pexels.com/photos/892618/pexels-photo-892618.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        userId: '1',
        price: '10',
      },
      {
        id: '2',
        title: 'Keys found',
        content: 'I found some keys on a bus stop yesterday. Will be happy to give them back to the owner.',
        date: '20.05.2019',
        updateDate: '21.05.2020',
        mail: 'johndoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/5930/wood-top-keys-lock.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        userId: '1',
        price: '30',
      },
      {
        id: '3',
        title: 'Japanese lessons',
        content: 'Professional Japanese teacher will give lessons to all who want to learn that beautiful language.',
        date: '20.01.2020',
        updateDate: '21.02.2020',
        mail: 'karinhoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/1498273/pexels-photo-1498273.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        userId: '2',
      },
      {
        id: '4',
        title: 'Looking for a roommate',
        content: 'Student is looking for someone to split costs of rent. Flat near university.',
        date: '10.10.2010',
        updateDate: '11.10.2010',
        mail: 'johndoe@example.com',
        phone: 123456789,
        status: 'published',
        image: 'https://images.pexels.com/photos/892618/pexels-photo-892618.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        userId: '1',
        price: '10',
      },
      {
        id: '5',
        title: 'Keys found',
        content: 'I found some keys on a bus stop yesterday. Will be happy to give them back to the owner.',
        date: '20.05.2019',
        updateDate: '21.05.2020',
        mail: 'johndoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/5930/wood-top-keys-lock.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        userId: '1',
        price: '30',
      },
      {
        id: '6',
        title: 'Japanese lessons',
        content: 'Professional Japanese teacher will give lessons to all who want to learn that beautiful language.',
        date: '20.01.2020',
        updateDate: '21.02.2020',
        mail: 'karinhoe@example.com',
        status: 'published',
        image: 'https://images.pexels.com/photos/1498273/pexels-photo-1498273.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        userId: '2',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    id: '1',
    logged: true,
  },
};
